server:
  port: 6201
spring:
  application:
    name: cloud-yblog-log
  redis:
    port: 6379
    password:
    host: localhost
    database: 12     #使用db12
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_yblog_log?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 18420163207
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录  慢查询：增删改查
    druid:
      connection-properties:
        druid:
          stat:
            mergeSql: true
      filter:
        stat:
          slow-sql-millis: 10
      test-on-borrow: false
      # 最长等待时间ms
      max-wait: 60000
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 30
      # 初始化时建立物理连接的个数
      initial-size: 5




mybatis:
  mapper-locations: classpath:mapper/*.xml

#自定义扫描包
scan:
  packageName: com.boot.controller
